trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

variables:
  ExecutableName: 'arduino-language-server'

jobs:
  - job: Linux_Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: GoTool@0
        inputs:
          version: '1.12'
      - script: |
          go build -o "$(Build.ArtifactStagingDirectory)/$(ExecutableName)_linux_amd64"
          go test ./...
        displayName: 'Generate builds'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        condition: succeededOrFailed()

  - job: MacOS_Build
    pool:
      vmImage: 'xcode9-macos10.13'
    steps:
      - task: GoTool@0
        inputs:
          version: '1.12'
      - script: |
          go build -o "$(Build.ArtifactStagingDirectory)/$(ExecutableName)_darwin_amd64"
          go test ./...
        displayName: 'Generate builds'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        condition: succeededOrFailed()

  - job: Windows_Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: GoTool@0
        inputs:
          version: '1.12'
      - script: |
          go build -o "$(Build.ArtifactStagingDirectory)/$(ExecutableName)_windows_amd64.exe"
          go test ./...
        displayName: 'Generate builds'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        condition: succeededOrFailed()
