trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

variables:
  ExecutableName: 'arduino-language-server'

jobs:
  - job: Build
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        mac:
          imageName: 'macos-10.13'
        windows:
          imageName: 'vs2017-win2016'
    pool:
      vmImage: $(imageName)
    steps:
      - task: GoTool@0
        inputs:
          version: '1.12'
      - script: |
          go build -o "$(Build.BinariesDirectory)/$(Agent.OS)_amd64/$(ExecutableName)"
          go test ./...
        displayName: 'Build and Test'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)/$(Agent.OS)_amd64'
          includeRootFolder: false
          archiveFile: '$(Build.BinariesDirectory)/archive/$(ExecutableName)_$(Agent.OS)_amd64.zip'
          archiveType: 'zip'
      - publish: '$(Build.BinariesDirectory)/archive'
        artifact: 'binary_$(Agent.OS)'
      - task: S3Upload@1
        condition: in(variables['Build.Reason'], 'Manual', 'Schedule')
        inputs:
          awsCredentials: 'language-server-s3-upload'
          bucketName: 'arduino-downloads-prod-beagle'
          sourceFolder: '$(Build.BinariesDirectory)/archive'
          globExpressions: '*.zip'
          targetFolder: 'arduino-language-server/nightly'
